#!/usr/bin/bash

#get first octets of network ip
ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3 | uniq > octets.txt

#set variable to have the value of octets.txt
OCTETS=$(cat octets.txt)

#create a new blank .txt
echo "" > $OCTETS.txt

#loop
for ip in {1..254}
do
	ping -c 1 $OCTETS.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $OCTETS.txt & done
cat $OCTETS.txt | sort > sorted_$OCTETS.txt

#perform scan
nmap -sS --top-ports 20 -iL sorted_$OCTETS.txt

exit





















